import React from 'react';
import '../CSS/PolicyPage.css';

const PolicyPage = () => {
  const currentDate = new Date().toLocaleDateString('en-US', { month: 'long', day: '2-digit', year: 'numeric' });

  return (
    <div className="policycontainer">
      <div className="card">
        {/* Header */}
        <h1 className="header">Privacy Policy</h1>

        {/* Privacy Policy Section */}
        <section className="section">
          <p className="text"><span className="text-bold">Effective Date:</span> {currentDate}</p>
          <p className="text">
            At AariWork <a href="https://aariwork.vibexio.ai/" className="link">aariwork.vibexio.ai</a>, we value your privacy and are committed to safeguarding your personal information. This policy explains how we collect and use your data when you enroll in a course.
          </p>

          <h3 className="subsection-title">1. What We Collect</h3>
          <p className="text">When you enroll in a course, we collect:</p>
          <ul className="list">
            <li className="list-item">Full Name</li>
            <li className="list-item">Mobile Number</li>
            <li className="list-item">Email Address</li>
          </ul>
          <p className="text">We do not collect sensitive personal data or store bank/card information. Payments are made via QR code generated by our system.</p>

          <h3 className="subsection-title">2. How We Use Your Data</h3>
          <p className="text">We use your information solely to:</p>
          <ul className="list">
            <li className="list-item">Confirm and manage your course enrollment</li>
            <li className="list-item">Send important updates or payment confirmations</li>
          </ul>
          <p className="text">Your data is never shared with third parties.</p>

          <h3 className="subsection-title">3. Payment Handling</h3>
          <p className="text">All payments are handled directly by the user via QR code scanning or UPI. No third-party payment processor is involved. Once payment is made, the confirmation is linked to your enrollment record.</p>
          <p className="text"><span className="text-bold">UPI ID:</span> kalaiarasi6067@okaxis</p>
          <p className="text"><span className="text-bold">Mobile:</span> +91 94457 38281</p>

          <h3 className="subsection-title">4. Data Security</h3>
          <p className="text">All personal information is stored securely and access is restricted to authorized personnel only.</p>

          <h3 className="subsection-title">5. Your Consent</h3>
          <p className="text">By submitting your details and proceeding with payment, you agree to this policy.</p>

          <h3 className="subsection-title">6. Contact</h3>
          <p className="text">For any queries, please contact:</p>
          <p className="text"><span className="text-bold">Email:</span> <a href="mailto:kalaiarasi6067@gmail.com" className="link">kalaiarasi6067@gmail.com</a></p>
          <p className="text"><span className="text-bold">Phone:</span>  +91 94457 38281</p>
        </section>

        {/* Terms & Conditions Section */}
        <section className="section">
        <h1 className="header">Terms & Conditions for Course Enrollment</h1>
          <p className="text">By enrolling in a course at AariWork and submitting your information, you agree to the following terms:</p>

          <h3 className="subsection-title">1. Enrollment Process</h3>
          <p className="text">You are required to submit your full name, mobile number, and email address. Your enrollment is confirmed only after full payment is received through the QR code or UPI ID provided.</p>

          <h3 className="subsection-title">2. Payment</h3>
          <p className="text">Payment is made by scanning a QR code or using the UPI ID (kalaiarasi6067@gmail.com). Please ensure the correct amount is paid. AariWork is not responsible for incorrect payments.</p>

          <h3 className="subsection-title">3. No Refund Policy</h3>
          <p className="text">Payments once made are non-refundable unless otherwise explicitly stated by the team.</p>

          <h3 className="subsection-title">4. Communication</h3>
          <p className="text">By enrolling, you consent to receive communication from AariWork regarding your course, updates, and future offerings.</p>

          <h3 className="subsection-title">5. Changes to Terms</h3>
          <p className="text">AariWork reserves the right to modify these terms at any time. Users will be notified of significant changes via email.</p>
        </section>
      </div>
    </div>
  );
};

export default PolicyPage;